file(MAKE_DIRECTORY "${CMAKE_BINARY_DIR}/cm")
set(CM_DIRS "analog" "digital" "spice2poly" "tlines" "xtradev" "xtraevt")
foreach(DIR ${CM_DIRS})
    set(CM_FILE "${SRC_DIR}/src/xspice/icm/${DIR}/${DIR}.cm")
    if(EXISTS "${CM_FILE}")
        file(COPY "${CM_FILE}" DESTINATION "${CMAKE_BINARY_DIR}/cm")
        message(STATUS "Copied ${DIR}.cm")
    endif()
endforeach()
