#include "simulation_panel.h"
#include "../items/voltage_source_item.h"
#include "../items/schematic_spice_directive_item.h"
#include "../items/schematic_page_item.h"
#include "../items/simulation_net_table_item.h"
#include "../items/wire_item.h"
#include "../../simulator/core/sim_value_parser.h"
#include "simulator/core/raw_data_parser.h"
#include "waveform_viewer.h"
#include "simulation_log_dialog.h"
#include "../../simulator/bridge/sim_audio_engine.h"
#include "theme_manager.h"
#include "config_manager.h"
#include "simulation_manager.h"
#include "../io/netlist_generator.h"
#include "../items/schematic_item.h"
#include "../analysis/spice_netlist_generator.h"
#include "../io/schematic_file_io.h"
#include "../../simulator/bridge/sim_schematic_bridge.h"
#include "../analysis/net_manager.h"
#include "../editor/schematic_editor.h"
#include "../dialogs/spice_step_dialog.h"
#include "../dialogs/pre_simulation_validation_dialog.h"
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QFormLayout>
#include <QGroupBox>
#include <QLabel>
#include <QDebug>
#include <QDateTime>
#include <QStandardPaths>
#include <QDir>
#include <QFile>
#include <QTemporaryFile>
#include <QTextStream>
#include <QTimer>
#include <QDialog>
#include <QDialogButtonBox>
#include <QChart>
#include <QChartView>
#include <QLineSeries>
#include <QValueAxis>
#include <QLogValueAxis>
#include <QCategoryAxis>
#include <QListWidget>
#include <QSplitter>
#include <QGraphicsView>
#include <QCheckBox>
#include <QSlider>
#include <QDoubleSpinBox>
#include <QToolBar>
#include <QTabWidget>
#include <QScrollArea>
#include <QFileDialog>
#include <QMenu>
#include <QColorDialog>
#include <QInputDialog>
#include <QApplication>
#include <QClipboard>
#include <QtConcurrent>
#include <QFutureWatcher>
#include <QShortcut>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QMessageBox>
#include <QTableWidget>
#include <QSet>
#include <QRegularExpression>
#include <algorithm>
#include <cmath>
#include "virtual_instruments.h"
#include "si_formatter.h"
#include "../../simulator/core/sim_math.h"

